Module Module3
    Dim tentarnovamente, parabens As Integer
    Sub verificar3()
        If par1 = par2 Then
            pontos = pontos + 1
            If par1 = 1 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox1.Visible = True
                Form4.PictureBox12.Visible = True
            ElseIf par1 = 2 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox2.Visible = True
                Form4.PictureBox20.Visible = True
            ElseIf par1 = 3 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox9.Visible = True
                Form4.PictureBox27.Visible = True
            ElseIf par1 = 4 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox3.Visible = True
                Form4.PictureBox30.Visible = True
            ElseIf par1 = 5 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox5.Visible = True
                Form4.PictureBox24.Visible = True
            ElseIf par1 = 6 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox16.Visible = True
                Form4.PictureBox14.Visible = True
            ElseIf par1 = 7 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox18.Visible = True
                Form4.PictureBox28.Visible = True
            ElseIf par1 = 8 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox6.Visible = True
                Form4.PictureBox31.Visible = True
            ElseIf par1 = 9 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox7.Visible = True
                Form4.PictureBox19.Visible = True
            ElseIf par1 = 10 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox10.Visible = True
                Form4.PictureBox29.Visible = True
            ElseIf par1 = 11 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox8.Visible = True
                Form4.PictureBox35.Visible = True
            ElseIf par1 = 12 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox17.Visible = True
                Form4.PictureBox33.Visible = True
            ElseIf par1 = 13 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox13.Visible = True
                Form4.PictureBox21.Visible = True
            ElseIf par1 = 14 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox22.Visible = True
                Form4.PictureBox32.Visible = True
            ElseIf par1 = 15 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox15.Visible = True
                Form4.PictureBox34.Visible = True
            ElseIf par1 = 16 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox36.Visible = True
                Form4.PictureBox4.Visible = True
            ElseIf par1 = 17 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox25.Visible = True
                Form4.PictureBox11.Visible = True
            ElseIf par1 = 18 Then
                Form4.Timer1.Start()
                Form4.PictureBox1.Enabled = False
                Form4.PictureBox2.Enabled = False
                Form4.PictureBox3.Enabled = False
                Form4.PictureBox4.Enabled = False
                Form4.PictureBox5.Enabled = False
                Form4.PictureBox6.Enabled = False
                Form4.PictureBox7.Enabled = False
                Form4.PictureBox8.Enabled = False
                Form4.PictureBox9.Enabled = False
                Form4.PictureBox10.Enabled = False
                Form4.PictureBox11.Enabled = False
                Form4.PictureBox12.Enabled = False
                Form4.PictureBox13.Enabled = False
                Form4.PictureBox14.Enabled = False
                Form4.PictureBox15.Enabled = False
                Form4.PictureBox16.Enabled = False
                Form4.PictureBox17.Enabled = False
                Form4.PictureBox18.Enabled = False
                Form4.PictureBox19.Enabled = False
                Form4.PictureBox20.Enabled = False
                Form4.PictureBox21.Enabled = False
                Form4.PictureBox22.Enabled = False
                Form4.PictureBox23.Enabled = False
                Form4.PictureBox24.Enabled = False
                Form4.PictureBox25.Enabled = False
                Form4.PictureBox26.Enabled = False
                Form4.PictureBox27.Enabled = False
                Form4.PictureBox28.Enabled = False
                Form4.PictureBox29.Enabled = False
                Form4.PictureBox30.Enabled = False
                Form4.PictureBox31.Enabled = False
                Form4.PictureBox32.Enabled = False
                Form4.PictureBox33.Enabled = False
                Form4.PictureBox34.Enabled = False
                Form4.PictureBox35.Enabled = False
                Form4.PictureBox36.Enabled = False

                Form4.PictureBox23.Visible = True
                Form4.PictureBox26.Visible = True
            End If

        Else
            tentarnovamente = MessageBox.Show("Tente Novamente!", "Você errou!", MessageBoxButtons.YesNo, MessageBoxIcon.Error)

            If tentarnovamente = vbYes Then

            ElseIf tentarnovamente = vbNo Then
                Form1.Show()
                Form4.Close()
            End If

            Form4.PictureBox1.Image = My.Resources.logo_kof
            Form4.PictureBox2.Image = My.Resources.logo_kof
            Form4.PictureBox3.Image = My.Resources.logo_kof
            Form4.PictureBox4.Image = My.Resources.logo_kof
            Form4.PictureBox5.Image = My.Resources.logo_kof
            Form4.PictureBox6.Image = My.Resources.logo_kof
            Form4.PictureBox7.Image = My.Resources.logo_kof
            Form4.PictureBox8.Image = My.Resources.logo_kof
            Form4.PictureBox9.Image = My.Resources.logo_kof
            Form4.PictureBox10.Image = My.Resources.logo_kof
            Form4.PictureBox11.Image = My.Resources.logo_kof
            Form4.PictureBox12.Image = My.Resources.logo_kof
            Form4.PictureBox13.Image = My.Resources.logo_kof
            Form4.PictureBox14.Image = My.Resources.logo_kof
            Form4.PictureBox15.Image = My.Resources.logo_kof
            Form4.PictureBox16.Image = My.Resources.logo_kof
            Form4.PictureBox17.Image = My.Resources.logo_kof
            Form4.PictureBox18.Image = My.Resources.logo_kof
            Form4.PictureBox19.Image = My.Resources.logo_kof
            Form4.PictureBox20.Image = My.Resources.logo_kof
            Form4.PictureBox21.Image = My.Resources.logo_kof
            Form4.PictureBox22.Image = My.Resources.logo_kof
            Form4.PictureBox23.Image = My.Resources.logo_kof
            Form4.PictureBox24.Image = My.Resources.logo_kof
            Form4.PictureBox25.Image = My.Resources.logo_kof
            Form4.PictureBox26.Image = My.Resources.logo_kof
            Form4.PictureBox27.Image = My.Resources.logo_kof
            Form4.PictureBox28.Image = My.Resources.logo_kof
            Form4.PictureBox29.Image = My.Resources.logo_kof
            Form4.PictureBox30.Image = My.Resources.logo_kof
            Form4.PictureBox31.Image = My.Resources.logo_kof
            Form4.PictureBox32.Image = My.Resources.logo_kof
            Form4.PictureBox33.Image = My.Resources.logo_kof
            Form4.PictureBox34.Image = My.Resources.logo_kof
            Form4.PictureBox35.Image = My.Resources.logo_kof
            Form4.PictureBox36.Image = My.Resources.logo_kof


            Form4.PictureBox1.Enabled = True
            Form4.PictureBox2.Enabled = True
            Form4.PictureBox3.Enabled = True
            Form4.PictureBox4.Enabled = True
            Form4.PictureBox5.Enabled = True
            Form4.PictureBox6.Enabled = True
            Form4.PictureBox7.Enabled = True
            Form4.PictureBox8.Enabled = True
            Form4.PictureBox9.Enabled = True
            Form4.PictureBox10.Enabled = True
            Form4.PictureBox11.Enabled = True
            Form4.PictureBox12.Enabled = True
            Form4.PictureBox13.Enabled = True
            Form4.PictureBox14.Enabled = True
            Form4.PictureBox15.Enabled = True
            Form4.PictureBox16.Enabled = True
            Form4.PictureBox17.Enabled = True
            Form4.PictureBox18.Enabled = True
            Form4.PictureBox19.Enabled = True
            Form4.PictureBox20.Enabled = True
            Form4.PictureBox21.Enabled = True
            Form4.PictureBox22.Enabled = True
            Form4.PictureBox23.Enabled = True
            Form4.PictureBox24.Enabled = True
            Form4.PictureBox25.Enabled = True
            Form4.PictureBox26.Enabled = True
            Form4.PictureBox27.Enabled = True
            Form4.PictureBox28.Enabled = True
            Form4.PictureBox29.Enabled = True
            Form4.PictureBox30.Enabled = True
            Form4.PictureBox31.Enabled = True
            Form4.PictureBox32.Enabled = True
            Form4.PictureBox33.Enabled = True
            Form4.PictureBox34.Enabled = True
            Form4.PictureBox35.Enabled = True
            Form4.PictureBox36.Enabled = True

        End If

        If pontos = 18 Then
            parabens = MessageBox.Show("Parábens!!! Você ganhou!!! e fez " & pontos & " pontos" & vbCrLf & "Deseja tentar novamente?", "Você Ganhou!", MessageBoxButtons.YesNo, MessageBoxIcon.Information)

            If parabens = vbYes Then

            ElseIf parabens = vbNo Then
                Form1.Show()
                Form4.Close()
            End If

            Form4.PictureBox1.Image = My.Resources.logo_kof
            Form4.PictureBox2.Image = My.Resources.logo_kof
            Form4.PictureBox3.Image = My.Resources.logo_kof
            Form4.PictureBox4.Image = My.Resources.logo_kof
            Form4.PictureBox5.Image = My.Resources.logo_kof
            Form4.PictureBox6.Image = My.Resources.logo_kof
            Form4.PictureBox7.Image = My.Resources.logo_kof
            Form4.PictureBox8.Image = My.Resources.logo_kof
            Form4.PictureBox9.Image = My.Resources.logo_kof
            Form4.PictureBox10.Image = My.Resources.logo_kof
            Form4.PictureBox11.Image = My.Resources.logo_kof
            Form4.PictureBox12.Image = My.Resources.logo_kof
            Form4.PictureBox13.Image = My.Resources.logo_kof
            Form4.PictureBox14.Image = My.Resources.logo_kof
            Form4.PictureBox15.Image = My.Resources.logo_kof
            Form4.PictureBox16.Image = My.Resources.logo_kof
            Form4.PictureBox17.Image = My.Resources.logo_kof
            Form4.PictureBox18.Image = My.Resources.logo_kof
            Form4.PictureBox19.Image = My.Resources.logo_kof
            Form4.PictureBox20.Image = My.Resources.logo_kof
            Form4.PictureBox21.Image = My.Resources.logo_kof
            Form4.PictureBox22.Image = My.Resources.logo_kof
            Form4.PictureBox23.Image = My.Resources.logo_kof
            Form4.PictureBox24.Image = My.Resources.logo_kof
            Form4.PictureBox25.Image = My.Resources.logo_kof
            Form4.PictureBox26.Image = My.Resources.logo_kof
            Form4.PictureBox27.Image = My.Resources.logo_kof
            Form4.PictureBox28.Image = My.Resources.logo_kof
            Form4.PictureBox29.Image = My.Resources.logo_kof
            Form4.PictureBox30.Image = My.Resources.logo_kof
            Form4.PictureBox31.Image = My.Resources.logo_kof
            Form4.PictureBox32.Image = My.Resources.logo_kof
            Form4.PictureBox33.Image = My.Resources.logo_kof
            Form4.PictureBox34.Image = My.Resources.logo_kof
            Form4.PictureBox35.Image = My.Resources.logo_kof
            Form4.PictureBox36.Image = My.Resources.logo_kof

            Form4.PictureBox1.Visible = True
            Form4.PictureBox2.Visible = True
            Form4.PictureBox3.Visible = True
            Form4.PictureBox4.Visible = True
            Form4.PictureBox5.Visible = True
            Form4.PictureBox6.Visible = True
            Form4.PictureBox7.Visible = True
            Form4.PictureBox8.Visible = True
            Form4.PictureBox9.Visible = True
            Form4.PictureBox10.Visible = True
            Form4.PictureBox11.Visible = True
            Form4.PictureBox12.Visible = True
            Form4.PictureBox13.Visible = True
            Form4.PictureBox14.Visible = True
            Form4.PictureBox15.Visible = True
            Form4.PictureBox16.Visible = True
            Form4.PictureBox17.Visible = True
            Form4.PictureBox18.Visible = True
            Form4.PictureBox19.Visible = True
            Form4.PictureBox20.Visible = True
            Form4.PictureBox21.Visible = True
            Form4.PictureBox22.Visible = True
            Form4.PictureBox23.Visible = True
            Form4.PictureBox24.Visible = True
            Form4.PictureBox25.Visible = True
            Form4.PictureBox26.Visible = True
            Form4.PictureBox27.Visible = True
            Form4.PictureBox28.Visible = True
            Form4.PictureBox29.Visible = True
            Form4.PictureBox30.Visible = True
            Form4.PictureBox31.Visible = True
            Form4.PictureBox32.Visible = True
            Form4.PictureBox33.Visible = True
            Form4.PictureBox34.Visible = True
            Form4.PictureBox35.Visible = True
            Form4.PictureBox36.Visible = True

            pontos = 0
            clique = False

        End If
    End Sub
End Module
